<?php

// Load Nette Framework or autoloader generated by Composer
require dirname(__FILE__) . '/../../Library/vendor/autoload.php';

Tracy\Debugger::$logSeverity = E_NOTICE;

$configurator = new \Nette\Configurator();

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode(TRUE);
$configurator->enableDebugger(dirname(__FILE__) . '/../log');

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(dirname(__FILE__) . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(dirname(__FILE__))
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(dirname(__FILE__) . '/config/config.neon');
$configurator->addConfig(dirname(__FILE__) . '/config/config.local.neon');
$container = $configurator->createContainer();

return $container;
